-- Drop
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE CHAT_LOG CASCADE CONSTRAINTS;
DROP TABLE CHAT_ATTACHMENT CASCADE CONSTRAINTS;

DROP TABLE CHAT_REQUEST CASCADE CONSTRAINTS;
DROP TABLE CHAT_REQUEST_CAT CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CHAT_LOG_NO;
DROP SEQUENCE SEQ_CHAT_REQUEST_NO;

-- Create
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE CHAT_LOG (
    CHAT_NO             NUMBER          PRIMARY KEY,
    QUOTATION_NO        NUMBER          NOT NULL,
    CHAT_SENDER         NUMBER          NOT NULL,
    CHAT_CONTENT        VARCHAR2(2000),
    CHAT_REQUEST        CHAR(1)         DEFAULT 'X'  CONSTRAINT CHAT_REQUEST_CHECK CHECK (CHAT_REQUEST IN ('O', 'X')),
    CHAT_ATTACHMENT     CHAR(1)         DEFAULT 'X'  CONSTRAINT CHAT_ATTACHMENT_CHECK CHECK (CHAT_ATTACHMENT IN ('O', 'X')),
    CHAT_READ           CHAR(1)         DEFAULT 'X'  CONSTRAINT CHAT_READ_CHECK CHECK (CHAT_READ IN ('O', 'X')),
    CHAT_STATUS         CHAR(1)         DEFAULT 'O'  CONSTRAINT CHAT_STATUS_CHECK CHECK (CHAT_STATUS IN ('O', 'X')),
    CHAT_ENROLL_DATE    TIMESTAMP       DEFAULT SYSDATE
)
;
CREATE SEQUENCE SEQ_CHAT_LOG_NO NOCACHE NOCYCLE;

CREATE TABLE CHAT_ATTACHMENT (
    CHAT_ATTACHMENT_NO      NUMBER          PRIMARY KEY, 
    CHAT_NO                 NUMBER          NOT NULL,
    ORIGIN_NAME             VARCHAR2(1000)  NOT NULL,
    CHANGE_NAME             VARCHAR2(1000)  NOT NULL,
    ENROLL_DATE             TIMESTAMP       ,
    STATUS                  CHAR(1)         DEFAULT 'O' CHECK ( STATUS IN ('O' , 'X') )
)
;

DROP TABLE CHAT_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE CHAT_ATTACHMENT (
    CHAT_ATTACHMENT_NO      NUMBER          PRIMARY KEY, 
    CHAT_NO                 NUMBER          NOT NULL,
    ORIGIN_NAME             VARCHAR2(1000)  NOT NULL,
    CHANGE_NAME             VARCHAR2(1000)  NOT NULL,
    ENROLL_DATE             TIMESTAMP       DEFAULT SYSDATE,
    STATUS                  CHAR(1)         DEFAULT 'O' CHECK ( STATUS IN ('O' , 'X') )
)
;



CREATE TABLE CHAT_REQUEST_CAT (
    CHAT_REQUEST_CAT_NO     NUMBER      PRIMARY KEY,
    CHAT_REQUEST_CAT_NAME   VARCHAR2(60)
)
;

DROP TABLE CHAT_REQUEST CASCADE CONSTRAINTS;
CREATE TABLE CHAT_REQUEST (
    REQUEST_NO              NUMBER          PRIMARY KEY,
    CHAT_LOG_NO             NUMBER          NOT NULL,
    REQUEST_CAT_NO          NUMBER          NOT NULL,
    REQUEST_CONTENT         VARCHAR2(3000),
    REQUEST_ENROLL_DATE     TIMESTAMP       DEFAULT SYSDATE,
    REQUEST_STATUS_NO       NUMBER,
    OPTION_NO               NUMBER,
    INPUT_NO                NUMBER
)
;
CREATE SEQUENCE SEQ_CHAT_REQUEST_NO NOCACHE NOCYCLE;



-- Sample Data
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
commit;
rollback;

INSERT INTO CHAT_REQUEST_CAT VALUES ( 100, '거래 완료');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 200, '거래 취소');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 300, '옵션 추가');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 400, '옵션 취소');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 500, '마감기간 단축');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 600, '마감기간 연장');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 700, '수정 요청');
INSERT INTO CHAT_REQUEST_CAT VALUES ( 800, '선금 요청');

SELECT CHAT_REQUEST_CAT_NO, CHAT_REQUEST_CAT_NAME
FROM CHAT_REQUEST_CAT
;

INSERT INTO CHAT_REQUEST
    ( REQUEST_NO, REQUEST_CAT_NO, QUOTATION_NO, CHAT_LOG_NO, REQUEST_SENDER, REQUEST_CONTENT, REQUEST_ENROLL_DATE, REQUEST_CHANGES )
VALUES (SEQ_REQUEST_NO.NEXTVAL, ?, ?, ?, ?, ?, DEFAULT, ?)
;


SELECT * FROM CHAT_LOG;

SELECT CHAT_SENDER
FROM CHAT_LOG
WHERE QUOTATION_NO = 1;

UPDATE CHAT_LOG SET CHAT_READ = 'O' WHERE QUOTATION_NO = 1 AND CHAT_SENDER = 2;

SELECT CHAT_NO, QUOTATION_NO, CHAT_SENDER, CHAT_SENDER, CHAT_CONTENT, CHAT_REQUEST, CHAT_ATTACHMENT, CHAT_READ, CHAT_STATUS, TO_CHAR(CHAT_ENROLL_DATE, 'YYYY/MM/DD HH24:MI') AS CHAT_ENROLL_DATE
FROM CHAT_LOG
WHERE QUOTATION_NO = 1 AND CHAT_NO > 0
ORDER BY CHAT_LOG.CHAT_ENROLL_DATE
;


select * from chat_log;

SELECT *
FROM CHAT_REQUEST
;

SELECT CHAT_NO
FROM (
    SELECT ROWNUM AS NO, CHAT_NO, CHAT_ENROLL_DATE
    FROM CHAT_LOG
    WHERE QUOTATION_NO = 1
    ORDER BY CHAT_LOG.CHAT_ENROLL_DATE DESC
)
WHERE NO = 1
;

SELECT ROWNUM, CHAT_NO, CHAT_ENROLL_DATE
FROM (
    SELECT ROWNUM AS NO, CHAT_NO, CHAT_ENROLL_DATE
    FROM CHAT_LOG
    WHERE QUOTATION_NO = 1
    ORDER BY CHAT_LOG.CHAT_ENROLL_DATE DESC
)
WHERE ROWNUM = 1
;

select * from chat_log where quotation_no = 1;

SELECT * FROM CHAT_REQUEST WHERE CHAT_LOG_NO = 1;

SELECT REQUEST_NO, REQUEST_CAT_NO, CHAT_REQUEST_CAT_NAME, REQUEST_CONTENT, REQUEST_ENROLL_DATE, REQUEST_STATUS_NO, OPTION_NO, INPUT_NO
FROM CHAT_REQUEST A
    JOIN CHAT_REQUEST_CAT B ON A.REQUEST_CAT_NO = B.CHAT_REQUEST_CAT_NO
WHERE CHAT_LOG_NO = 4
;
