/*
-- 계정생성
CREATE USER C##SEMI IDENTIFIED BY "1234";
-- 권한 부여
GRANT CONNECT, RESOURCE TO C##SEMI;
ALTER USER C##SEMI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; -- 안하면 INSERT 시 오류 발생
*/

-- MEMBER
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(100) NOT NULL  UNIQUE,
    PWD VARCHAR2(100) NOT NULL,
    NICK VARCHAR2(100) UNIQUE
);
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

-- BOARD
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO)
);
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;



--------------------------------------------------------------------------------
COMMIT;
ROLLBACK;


SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '0000', 'admin01');


SELECT * FROM BOARD;
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_BOARD_NO.NEXTVAL, '제목', '내용', 1);

SELECT BOARD.NO, NICK FROM BOARD JOIN MEMBER ON BOARD.WRITER_NO = MEMBER.NO;
