/*
-- USER
DROP TABLE "USER" CASCADE CONSTRAINTS;
CREATE TABLE "USER" (
	"NO"	NUMBER		NOT NULL,
	"DEPARTMENT_NO"	NUMBER		NOT NULL,
	"RANK_NO"	NUMBER		NOT NULL,
	"POSITION_NO"	NUMBER		NOT NULL,
	"STATE_NO"	NUMBER		NOT NULL,
	"AGENT"	NUMBER		NULL,
	"DIVISION_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(100)		NOT NULL,
	"PWD"	VARCHAR2(100)		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"BIRTH_DATE"	CHAR(8)		NOT NULL,
	"PROFILE"	VARCHAR2(300)		NULL,
	"LINE_INTRO"	VARCHAR2(300)		NULL,
	"ADDRESS"	VARCHAR2(300)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"MAIL"	VARCHAR2(100)		NOT NULL,
	"REGISTRATION_DATE"	CHAR(8)		NOT NULL,
	"LEAVE_REASON"	VARCHAR2(500)		NULL,
	"LEAVE_DATE"	CHAR(8)		NULL,
	"OFFICE_NUMBER"	CHAR(11)		NULL,
	"LEAVE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"CAPACITY"	NUMBER	DEFAULT 500	NOT NULL
);
*/

